services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thirty
      POSTGRES_PASSWORD: thirty
      POSTGRES_DB: thirty
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
